"""empty message

Revision ID: c8fd13d709f4
Revises: 
Create Date: 2024-10-15 16:04:48.437392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fd13d709f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Customers')
    op.drop_table('Customer_Orders')
    op.drop_table('Customer_Order_Items')
    op.drop_table('INVENTORY')
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.String(length=75), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sub_category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('size', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('Size')
        batch_op.drop_column('Product_Name')
        batch_op.drop_column('Category')
        batch_op.drop_column('Price')
        batch_op.drop_column('Product_ID')
        batch_op.drop_column('Sub_Category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sub_Category', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Product_ID', sa.NVARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Price', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Category', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Product_Name', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Size', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('size')
        batch_op.drop_column('price')
        batch_op.drop_column('sub_category')
        batch_op.drop_column('category')
        batch_op.drop_column('product_name')
        batch_op.drop_column('product_id')

    op.create_table('INVENTORY',
    sa.Column('Product_ID', sa.NVARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Statee', sa.NVARCHAR(length=75), autoincrement=False, nullable=False),
    sa.Column('Quantity_In_Hand', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Country', sa.VARCHAR(length=75, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('City', sa.VARCHAR(length=75, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Product_ID'], ['Products.Product_ID'], name='FK__INVENTORY__Produ__440B1D61'),
    sa.PrimaryKeyConstraint('Statee', 'Product_ID', name='PK__INVENTOR__83965F656404BAD6')
    )
    op.create_table('Customer_Order_Items',
    sa.Column('Order_ID', sa.NVARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Product_ID', sa.NVARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Sales', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Order_ID'], ['Customer_Orders.Order_ID'], name='FK__Customer___Order__403A8C7D'),
    sa.ForeignKeyConstraint(['Product_ID'], ['Products.Product_ID'], name='FK__Customer___Produ__412EB0B6'),
    sa.PrimaryKeyConstraint('Order_ID', 'Product_ID', name='PK__Customer__48672C229C850B7F')
    )
    op.create_table('Customer_Orders',
    sa.Column('Order_ID', sa.NVARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Customer_ID', sa.NVARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Order_Date', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('Order_Status', sa.VARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Order_Priority', sa.VARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Customer_ID'], ['Customers.Customer_ID'], name='FK__Customer___Custo__3D5E1FD2'),
    sa.PrimaryKeyConstraint('Order_ID', name='PK__Customer__F1E4639BC4EED94D')
    )
    op.create_table('Customers',
    sa.Column('Customer_ID', sa.NVARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Customer_Name', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Segment', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Email', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Password_hash', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Customer_ID', name='PK__Customer__8CB286B99B79D08F')
    )
    # ### end Alembic commands ###
